// app/frontend/src/routes/fuel/reports/sunday-fueling/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api';
  import { _ } from '$lib/i18n';
  import DataTable from '$lib/components/DataTable.svelte';

  let isLoading = true;
  let transactions = [];
  let filteredTransactions = [];
  let selectedVehicleId = 'all';
  let selectedMonth = '';
  let customStartDate = '';
  let customEndDate = '';
  let vehicles = [];
  let totalFuelCost = 0;
  let totalFuelVolume = 0;
  let totalTransactions = 0;
  let uniqueVehicles = 0;

  // Data table columns
  const columns = [
    {
      key: 'transactionDate',
      label: $_('fuel.transactionDate'),
      sortable: true,
      render: (value) => {
        const date = new Date(value);
        // Format as dd/mm/yyyy HH:MM
        const day = String(date.getDate()).padStart(2, '0');
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const year = date.getFullYear();
        const hours = String(date.getHours()).padStart(2, '0');
        const minutes = String(date.getMinutes()).padStart(2, '0');
        return `${day}/${month}/${year} ${hours}:${minutes}`;
      }
    },
    {
      key: 'vehicle',
      label: $_('fuel.vehicle'),
      sortable: true,
      render: (value, row) => {
        return row.vehicle?.licensePlate || 'N/A';
      }
    },
    {
      key: 'vehicleCode',
      label: $_('vehicles.vehicleCode'),
      sortable: true,
      render: (value, row) => {
        return row.vehicle?.vehicleCode || 'N/A';
      }
    },
    {
      key: 'driver',
      label: $_('fuel.driver'),
      sortable: true,
      render: (value, row) => {
        return row.driver?.fullName || 'N/A';
      }
    },
    {
      key: 'fuelStation',
      label: $_('fuel.fuelStation'),
      sortable: true,
      render: (value, row) => {
        return row.fuelStation?.stationName || 'N/A';
      }
    },
    {
      key: 'fuelType',
      label: $_('fuel.fuelType'),
      sortable: true,
      render: (value, row) => {
        return row.fuelType?.fuelName || 'N/A';
      }
    },
    {
      key: 'quantity',
      label: $_('fuel.quantity'),
      sortable: true,
      render: (value) => `${parseFloat(value || 0).toFixed(2)} L`
    },
    {
      key: 'totalAmount',
      label: $_('fuel.totalAmount'),
      sortable: true,
      render: (value, row) => `${parseFloat(value || 0).toFixed(2)} ${row.currency || 'RON'}`
    },
    {
      key: 'odometerReading',
      label: $_('fuel.odometerReading'),
      sortable: true,
      render: (value) => value ? `${parseInt(value).toLocaleString()} km` : 'N/A'
    }
  ];

  onMount(async () => {
    const token = localStorage.getItem('token');
    if (!token) {
      goto('/');
      return;
    }

    // Set default dates - last 3 months
    const today = new Date();
    customEndDate = today.toISOString().split('T')[0];
    const threeMonthsAgo = new Date(today);
    threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
    customStartDate = threeMonthsAgo.toISOString().split('T')[0];

    await loadVehicles();
    await loadSundayTransactions();
  });

  async function loadVehicles() {
    try {
      const response = await api.getVehicles({ limit: 1000 });
      vehicles = response.data || [];
    } catch (error) {
      console.error('Failed to load vehicles:', error);
      vehicles = [];
    }
  }

  async function loadSundayTransactions() {
    isLoading = true;
    try {
      const params = {
        limit: 10000
      };

      if (customStartDate) {
        params.startDate = customStartDate;
      }
      if (customEndDate) {
        params.endDate = customEndDate;
      }

      const response = await api.getFuelTransactions(params);
      const allTransactions = response.data || [];

      // Filter for Sunday transactions
      transactions = allTransactions.filter(transaction => {
        const date = new Date(transaction.transactionDate);
        return date.getDay() === 0; // 0 = Sunday
      });

      applyFilters();
    } catch (error) {
      console.error('Failed to load Sunday fuel transactions:', error);
      transactions = [];
      filteredTransactions = [];
    } finally {
      isLoading = false;
    }
  }

  function applyFilters() {
    filteredTransactions = transactions.filter(transaction => {
      // Vehicle filter
      if (selectedVehicleId !== 'all' && transaction.vehicleId !== parseInt(selectedVehicleId)) {
        return false;
      }

      // Month filter
      if (selectedMonth) {
        const transactionMonth = new Date(transaction.transactionDate).toISOString().substring(0, 7);
        if (transactionMonth !== selectedMonth) {
          return false;
        }
      }

      return true;
    });

    calculateStatistics();
  }

  function calculateStatistics() {
    totalFuelCost = filteredTransactions.reduce((sum, t) => sum + parseFloat(t.totalAmount || 0), 0);
    totalFuelVolume = filteredTransactions.reduce((sum, t) => sum + parseFloat(t.quantity || 0), 0);
    totalTransactions = filteredTransactions.length;
    uniqueVehicles = new Set(filteredTransactions.map(t => t.vehicleId)).size;
  }

  function handleVehicleChange() {
    applyFilters();
  }

  function handleMonthChange() {
    applyFilters();
  }

  function handleDateRangeChange() {
    loadSundayTransactions();
  }

  function exportToCSV() {
    if (filteredTransactions.length === 0) {
      alert($_('fuel.reports.noDataToExport'));
      return;
    }

    // Create CSV content
    const headers = [
      'Data',
      'Vehicul',
      'Cod Vehicul',
      'Sofer',
      'Statie',
      'Tip Combustibil',
      'Cantitate (L)',
      'Pret Total (RON)',
      'KM'
    ];

    const rows = filteredTransactions.map(t => {
      const date = new Date(t.transactionDate);
      const day = String(date.getDate()).padStart(2, '0');
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const year = date.getFullYear();
      const hours = String(date.getHours()).padStart(2, '0');
      const minutes = String(date.getMinutes()).padStart(2, '0');
      const formattedDate = `${day}/${month}/${year} ${hours}:${minutes}`;

      return [
        formattedDate,
        t.vehicle?.licensePlate || 'N/A',
        t.vehicle?.vehicleCode || 'N/A',
        t.driver?.fullName || 'N/A',
        t.fuelStation?.stationName || 'N/A',
        t.fuelType?.fuelName || 'N/A',
        parseFloat(t.quantity || 0).toFixed(2),
        parseFloat(t.totalAmount || 0).toFixed(2),
        t.odometerReading || 'N/A'
      ];
    });

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    // Create download
    const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `alimentari-duminica-${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  }

  // Get unique months from transactions for month filter
  $: uniqueMonths = [...new Set(
    transactions.map(t => new Date(t.transactionDate).toISOString().substring(0, 7))
  )].sort().reverse();
</script>

<div class="container mx-auto px-4 py-8">
  <!-- Header -->
  <div class="mb-8">
    <h1 class="text-3xl font-bold text-gray-900 mb-2">
      {$_('fuel.reports.sundayFueling.title')}
    </h1>
    <p class="text-gray-600">
      {$_('fuel.reports.sundayFueling.description')}
    </p>
  </div>

  <!-- Filters -->
  <div class="bg-white rounded-lg shadow-md p-6 mb-6">
    <h2 class="text-lg font-semibold text-gray-900 mb-4">{$_('common.filters')}</h2>
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
      <!-- Date Range -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          {$_('fuel.reports.startDate')}
        </label>
        <input
          type="date"
          bind:value={customStartDate}
          on:change={handleDateRangeChange}
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          {$_('fuel.reports.endDate')}
        </label>
        <input
          type="date"
          bind:value={customEndDate}
          on:change={handleDateRangeChange}
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <!-- Vehicle Filter -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          {$_('fuel.vehicle')}
        </label>
        <select
          bind:value={selectedVehicleId}
          on:change={handleVehicleChange}
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="all">{$_('fuel.reports.allVehicles')}</option>
          {#each vehicles as vehicle}
            <option value={vehicle.id}>
              {vehicle.licensePlate} - {vehicle.vehicleCode}
            </option>
          {/each}
        </select>
      </div>

      <!-- Month Filter -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          {$_('fuel.reports.month')}
        </label>
        <select
          bind:value={selectedMonth}
          on:change={handleMonthChange}
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">{$_('fuel.reports.allMonths')}</option>
          {#each uniqueMonths as month}
            <option value={month}>
              {new Date(month + '-01').toLocaleDateString('ro-RO', { year: 'numeric', month: 'long' })}
            </option>
          {/each}
        </select>
      </div>
    </div>
  </div>

  <!-- Statistics Cards -->
  <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
    <div class="bg-white rounded-lg shadow-md p-6">
      <div class="text-sm text-gray-600 mb-1">{$_('fuel.reports.totalTransactions')}</div>
      <div class="text-2xl font-bold text-blue-600">{totalTransactions}</div>
    </div>

    <div class="bg-white rounded-lg shadow-md p-6">
      <div class="text-sm text-gray-600 mb-1">{$_('fuel.reports.uniqueVehicles')}</div>
      <div class="text-2xl font-bold text-green-600">{uniqueVehicles}</div>
    </div>

    <div class="bg-white rounded-lg shadow-md p-6">
      <div class="text-sm text-gray-600 mb-1">{$_('fuel.reports.totalFuelVolume')}</div>
      <div class="text-2xl font-bold text-purple-600">{totalFuelVolume.toFixed(2)} L</div>
    </div>

    <div class="bg-white rounded-lg shadow-md p-6">
      <div class="text-sm text-gray-600 mb-1">{$_('fuel.reports.totalCost')}</div>
      <div class="text-2xl font-bold text-red-600">{totalFuelCost.toFixed(2)} RON</div>
    </div>
  </div>

  <!-- Export Button -->
  <div class="mb-4 flex justify-end">
    <button
      on:click={exportToCSV}
      disabled={filteredTransactions.length === 0}
      class="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
    >
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      {$_('fuel.reports.exportToCSV')}
    </button>
  </div>

  <!-- Transactions Table -->
  <div class="bg-white rounded-lg shadow-md overflow-hidden">
    {#if isLoading}
      <div class="p-8 text-center">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
        <p class="mt-4 text-gray-600">{$_('common.loading')}</p>
      </div>
    {:else if filteredTransactions.length === 0}
      <div class="p-8 text-center text-gray-600">
        <svg class="w-16 h-16 mx-auto mb-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        <p>{$_('fuel.reports.sundayFueling.noTransactions')}</p>
      </div>
    {:else}
      <DataTable
        {columns}
        data={filteredTransactions}
        itemsPerPage={20}
      />
    {/if}
  </div>
</div>

// app/frontend-next/src/app/(dashboard)/fuel/reports/sunday-fueling/page.tsx
'use client';

import { useState, useMemo } from 'react';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  ArrowLeft,
  Download,
  Calendar,
  Car,
  Users,
  Fuel,
  DollarSign,
  FileText,
} from 'lucide-react';
import { fuelApi, vehiclesApi } from '@/lib/api';
import type { FuelTransaction, Vehicle } from '@/types';

function StatCard({
  title,
  value,
  suffix = '',
  icon: Icon,
  color,
  loading = false,
}: {
  title: string;
  value: string | number;
  suffix?: string;
  icon: React.ElementType;
  color: string;
  loading?: boolean;
}) {
  return (
    <Card>
      <CardContent className="pt-6">
        <div className="flex items-center gap-4">
          <div className={`p-3 rounded-full ${color}`}>
            <Icon className="h-6 w-6" />
          </div>
          <div>
            <p className="text-sm text-slate-500">{title}</p>
            {loading ? (
              <Skeleton className="h-8 w-24" />
            ) : (
              <p className="text-2xl font-bold">
                {typeof value === 'number' ? value.toLocaleString('ro-RO', { maximumFractionDigits: 2 }) : value}
                {suffix && <span className="text-sm font-normal text-slate-500 ml-1">{suffix}</span>}
              </p>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export default function SundayFuelingReportPage() {
  // Get default dates - last 3 months
  const getDefaultDates = () => {
    const today = new Date();
    const threeMonthsAgo = new Date(today);
    threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
    return {
      start: threeMonthsAgo.toISOString().split('T')[0],
      end: today.toISOString().split('T')[0],
    };
  };

  const defaultDates = getDefaultDates();
  const [selectedVehicleId, setSelectedVehicleId] = useState<string>('all');
  const [selectedMonth, setSelectedMonth] = useState<string>('');
  const [customStartDate, setCustomStartDate] = useState<string>(defaultDates.start);
  const [customEndDate, setCustomEndDate] = useState<string>(defaultDates.end);

  // Fetch vehicles
  const { data: vehiclesData } = useQuery({
    queryKey: ['vehicles', 'all'],
    queryFn: () => vehiclesApi.getAll({ pageSize: 1000 }),
  });

  const vehicles = vehiclesData?.data || [];

  // Fetch fuel transactions
  const { data: transactionsData, isLoading } = useQuery({
    queryKey: ['fuel', 'transactions', 'sunday', customStartDate, customEndDate],
    queryFn: () =>
      fuelApi.getAll({
        dateFrom: customStartDate,
        dateTo: customEndDate,
        pageSize: 10000,
      }),
    enabled: !!customStartDate && !!customEndDate,
  });

  // Filter for Sunday transactions
  const sundayTransactions = useMemo(() => {
    const allTransactions = transactionsData?.data || [];
    return allTransactions.filter((transaction: FuelTransaction) => {
      const date = new Date(transaction.transactionDate);
      return date.getDay() === 0; // 0 = Sunday
    });
  }, [transactionsData]);

  // Apply filters
  const filteredTransactions = useMemo(() => {
    return sundayTransactions.filter((transaction: FuelTransaction) => {
      // Vehicle filter
      if (selectedVehicleId !== 'all' && transaction.vehicleId !== parseInt(selectedVehicleId)) {
        return false;
      }

      // Month filter
      if (selectedMonth) {
        const transactionMonth = new Date(transaction.transactionDate).toISOString().substring(0, 7);
        if (transactionMonth !== selectedMonth) {
          return false;
        }
      }

      return true;
    });
  }, [sundayTransactions, selectedVehicleId, selectedMonth]);

  // Calculate statistics
  const stats = useMemo(() => {
    return {
      totalTransactions: filteredTransactions.length,
      uniqueVehicles: new Set(filteredTransactions.map((t: FuelTransaction) => t.vehicleId)).size,
      totalFuelVolume: filteredTransactions.reduce((sum: number, t: FuelTransaction) => sum + (parseFloat(String(t.quantity)) || 0), 0),
      totalFuelCost: filteredTransactions.reduce((sum: number, t: FuelTransaction) => sum + (parseFloat(String(t.totalCost)) || 0), 0),
    };
  }, [filteredTransactions]);

  // Get unique months for filter
  const uniqueMonths = useMemo(() => {
    return [...new Set(
      sundayTransactions.map((t: FuelTransaction) => new Date(t.transactionDate).toISOString().substring(0, 7))
    )].sort().reverse();
  }, [sundayTransactions]);

  // Export to CSV
  const exportToCSV = () => {
    if (filteredTransactions.length === 0) {
      alert('Nu există date pentru export');
      return;
    }

    const headers = [
      'Data',
      'Vehicul',
      'Cod Vehicul',
      'Șofer',
      'Stație',
      'Tip Combustibil',
      'Cantitate (L)',
      'Preț Total (RON)',
      'KM',
    ];

    const rows = filteredTransactions.map((t: FuelTransaction) => {
      const date = new Date(t.transactionDate);
      const day = String(date.getDate()).padStart(2, '0');
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const year = date.getFullYear();
      const hours = String(date.getHours()).padStart(2, '0');
      const minutes = String(date.getMinutes()).padStart(2, '0');
      const formattedDate = `${day}/${month}/${year} ${hours}:${minutes}`;

      return [
        formattedDate,
        t.vehicle?.licensePlate || 'N/A',
        t.vehicle?.vehicleCode || 'N/A',
        t.driver ? `${t.driver.firstName} ${t.driver.lastName}` : 'N/A',
        t.fuelStation?.name || 'N/A',
        t.fuelType?.name || 'N/A',
        parseFloat(String(t.quantity) || '0').toFixed(2),
        parseFloat(String(t.totalCost) || '0').toFixed(2),
        t.odometer || 'N/A',
      ];
    });

    const csvContent = [
      headers.join(','),
      ...rows.map((row: (string | number)[]) => row.map((cell: string | number) => `"${cell}"`).join(',')),
    ].join('\n');

    const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `alimentari-duminica-${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Button variant="ghost" size="sm" asChild>
              <Link href="/fuel/reports">
                <ArrowLeft className="h-4 w-4 mr-1" />
                Înapoi la Rapoarte
              </Link>
            </Button>
          </div>
          <h1 className="text-3xl font-bold tracking-tight">Alimentări Duminică</h1>
          <p className="text-slate-500 dark:text-slate-400">
            Raport cu toate alimentările efectuate în zilele de duminică
          </p>
        </div>
        <Button
          variant="outline"
          onClick={exportToCSV}
          disabled={filteredTransactions.length === 0}
        >
          <Download className="mr-2 h-4 w-4" />
          Export CSV
        </Button>
      </div>

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle>Filtre</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="space-y-2">
              <Label>Data început</Label>
              <Input
                type="date"
                value={customStartDate}
                onChange={(e) => setCustomStartDate(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Data sfârșit</Label>
              <Input
                type="date"
                value={customEndDate}
                onChange={(e) => setCustomEndDate(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Vehicul</Label>
              <Select value={selectedVehicleId} onValueChange={setSelectedVehicleId}>
                <SelectTrigger>
                  <SelectValue placeholder="Selectează vehiculul" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Toate vehiculele</SelectItem>
                  {vehicles.map((vehicle: Vehicle) => (
                    <SelectItem key={vehicle.id} value={String(vehicle.id)}>
                      {vehicle.licensePlate} - {vehicle.vehicleCode}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Luna</Label>
              <Select value={selectedMonth} onValueChange={setSelectedMonth}>
                <SelectTrigger>
                  <SelectValue placeholder="Toate lunile" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">Toate lunile</SelectItem>
                  {uniqueMonths.map((month: string) => (
                    <SelectItem key={month} value={month}>
                      {new Date(month + '-01').toLocaleDateString('ro-RO', { year: 'numeric', month: 'long' })}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Statistics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <StatCard
          title="Total Tranzacții"
          value={stats.totalTransactions}
          icon={Calendar}
          color="bg-blue-100 dark:bg-blue-900/30 text-blue-600"
          loading={isLoading}
        />
        <StatCard
          title="Vehicule Unice"
          value={stats.uniqueVehicles}
          icon={Car}
          color="bg-green-100 dark:bg-green-900/30 text-green-600"
          loading={isLoading}
        />
        <StatCard
          title="Combustibil Total"
          value={stats.totalFuelVolume.toFixed(2)}
          suffix="L"
          icon={Fuel}
          color="bg-purple-100 dark:bg-purple-900/30 text-purple-600"
          loading={isLoading}
        />
        <StatCard
          title="Cost Total"
          value={stats.totalFuelCost.toFixed(2)}
          suffix="RON"
          icon={DollarSign}
          color="bg-red-100 dark:bg-red-900/30 text-red-600"
          loading={isLoading}
        />
      </div>

      {/* Transactions Table */}
      <Card>
        <CardHeader>
          <CardTitle>Tranzacții Duminică</CardTitle>
          <CardDescription>
            {filteredTransactions.length} alimentări găsite
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-4">
              <Skeleton className="h-12 w-full" />
              <Skeleton className="h-12 w-full" />
              <Skeleton className="h-12 w-full" />
            </div>
          ) : filteredTransactions.length === 0 ? (
            <div className="py-12 text-center">
              <FileText className="h-12 w-12 mx-auto text-slate-400 mb-4" />
              <h3 className="text-lg font-medium mb-2">Nu există alimentări duminică</h3>
              <p className="text-sm text-slate-500">
                Nu au fost găsite tranzacții pentru zilele de duminică în perioada selectată.
              </p>
            </div>
          ) : (
            <div className="rounded-md border overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Data</TableHead>
                    <TableHead>Vehicul</TableHead>
                    <TableHead>Cod Vehicul</TableHead>
                    <TableHead>Șofer</TableHead>
                    <TableHead>Stație</TableHead>
                    <TableHead>Tip Combustibil</TableHead>
                    <TableHead className="text-right">Cantitate</TableHead>
                    <TableHead className="text-right">Valoare</TableHead>
                    <TableHead className="text-right">KM</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredTransactions.map((transaction: FuelTransaction) => {
                    const date = new Date(transaction.transactionDate);
                    const formattedDate = `${String(date.getDate()).padStart(2, '0')}/${String(date.getMonth() + 1).padStart(2, '0')}/${date.getFullYear()} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;

                    return (
                      <TableRow key={transaction.id}>
                        <TableCell className="font-medium">{formattedDate}</TableCell>
                        <TableCell>{transaction.vehicle?.licensePlate || 'N/A'}</TableCell>
                        <TableCell>{transaction.vehicle?.vehicleCode || 'N/A'}</TableCell>
                        <TableCell>{transaction.driver ? `${transaction.driver.firstName} ${transaction.driver.lastName}` : 'N/A'}</TableCell>
                        <TableCell>{transaction.fuelStation?.name || 'N/A'}</TableCell>
                        <TableCell>{transaction.fuelType?.name || 'N/A'}</TableCell>
                        <TableCell className="text-right">{parseFloat(String(transaction.quantity) || '0').toFixed(2)} L</TableCell>
                        <TableCell className="text-right">{parseFloat(String(transaction.totalCost) || '0').toFixed(2)} RON</TableCell>
                        <TableCell className="text-right">
                          {transaction.odometer ? `${parseInt(String(transaction.odometer)).toLocaleString()} km` : 'N/A'}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
