// app/frontend-next/src/components/shared/photo-manager.tsx
'use client';

import { useState, useCallback } from 'react';
import Image from 'next/image';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Skeleton } from '@/components/ui/skeleton';
import {
  ImageIcon,
  Upload,
  Download,
  Trash2,
  Plus,
  Star,
  Loader2,
  X,
  ZoomIn,
} from 'lucide-react';
import { format } from 'date-fns';
import { ro } from 'date-fns/locale';
import {
  usePhotos,
  useUploadPhoto,
  useDeletePhoto,
} from '@/lib/hooks/use-documents';
import { documentsApi, EntityType, Photo } from '@/lib/api/documents';

interface PhotoManagerProps {
  entityType: EntityType;
  entityId: number;
  title?: string;
  description?: string;
  readOnly?: boolean;
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function PhotoManager({
  entityType,
  entityId,
  title = 'Fotografii',
  description = 'Gestionează fotografiile',
  readOnly = false,
}: PhotoManagerProps) {
  const [isUploadOpen, setIsUploadOpen] = useState(false);
  const [previewPhoto, setPreviewPhoto] = useState<Photo | null>(null);
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [uploadPreview, setUploadPreview] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    photoName: '',
    description: '',
    isPrimary: false,
  });

  const { data: photos, isLoading } = usePhotos(entityType, entityId);
  const uploadMutation = useUploadPhoto();
  const deleteMutation = useDeletePhoto();

  const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate it's an image
      if (!file.type.startsWith('image/')) {
        return;
      }
      setUploadFile(file);

      // Create preview
      const reader = new FileReader();
      reader.onload = (e) => {
        setUploadPreview(e.target?.result as string);
      };
      reader.readAsDataURL(file);

      if (!formData.photoName) {
        setFormData(prev => ({ ...prev, photoName: file.name.replace(/\.[^/.]+$/, '') }));
      }
    }
  }, [formData.photoName]);

  const handleUpload = async () => {
    if (!uploadFile || !formData.photoName) return;

    await uploadMutation.mutateAsync({
      file: uploadFile,
      data: {
        photoName: formData.photoName,
        entityType,
        entityId,
        description: formData.description || undefined,
        isPrimary: formData.isPrimary,
      },
    });

    setIsUploadOpen(false);
    setUploadFile(null);
    setUploadPreview(null);
    setFormData({
      photoName: '',
      description: '',
      isPrimary: false,
    });
  };

  const handleDelete = async () => {
    if (!deleteId) return;
    await deleteMutation.mutateAsync({ id: deleteId, entityType, entityId });
    setDeleteId(null);
  };

  const handleDownload = (photo: Photo) => {
    const url = documentsApi.getPhotoDownloadUrl(photo.id);
    window.open(url, '_blank');
  };

  const primaryPhoto = photos?.find(p => p.isPrimary);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <ImageIcon className="h-5 w-5" />
              {title}
            </CardTitle>
            <CardDescription>{description}</CardDescription>
          </div>
          {!readOnly && (
            <Button onClick={() => setIsUploadOpen(true)}>
              <Plus className="h-4 w-4 mr-2" />
              Adaugă Fotografie
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className="aspect-square rounded-lg" />
            ))}
          </div>
        ) : !photos || photos.length === 0 ? (
          <div className="text-center py-8">
            <ImageIcon className="mx-auto h-12 w-12 text-slate-400" />
            <h3 className="mt-4 text-lg font-semibold">Nu există fotografii</h3>
            <p className="text-sm text-slate-500">
              {readOnly
                ? 'Nu au fost încărcate fotografii.'
                : 'Adaugă prima fotografie folosind butonul de mai sus.'}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {photos.map((photo) => (
              <div
                key={photo.id}
                className="group relative aspect-square rounded-lg overflow-hidden border bg-slate-100 dark:bg-slate-800"
              >
                {/* Photo thumbnail */}
                <Image
                  src={documentsApi.getPhotoUrl(photo.id)}
                  alt={photo.photoName}
                  fill
                  className="object-cover"
                  sizes="(max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
                />

                {/* Primary badge */}
                {photo.isPrimary && (
                  <Badge className="absolute top-2 left-2 gap-1 bg-yellow-500">
                    <Star className="h-3 w-3" />
                    Principal
                  </Badge>
                )}

                {/* Hover overlay */}
                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => setPreviewPhoto(photo)}
                  >
                    <ZoomIn className="h-4 w-4" />
                  </Button>
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => handleDownload(photo)}
                  >
                    <Download className="h-4 w-4" />
                  </Button>
                  {!readOnly && (
                    <Button
                      size="sm"
                      variant="destructive"
                      onClick={() => setDeleteId(photo.id)}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  )}
                </div>

                {/* Photo info */}
                <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-2">
                  <p className="text-xs text-white font-medium truncate">{photo.photoName}</p>
                  <p className="text-xs text-white/70">{formatFileSize(photo.fileSize)}</p>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Photo count and primary info */}
        {photos && photos.length > 0 && (
          <div className="mt-4 flex items-center gap-4 text-sm text-slate-500">
            <span>{photos.length} fotografi{photos.length === 1 ? 'e' : 'i'}</span>
            {primaryPhoto && (
              <span className="flex items-center gap-1">
                <Star className="h-3 w-3 text-yellow-500" />
                {primaryPhoto.photoName}
              </span>
            )}
          </div>
        )}
      </CardContent>

      {/* Upload Dialog */}
      <Dialog open={isUploadOpen} onOpenChange={setIsUploadOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Încarcă Fotografie</DialogTitle>
            <DialogDescription>
              Selectează o imagine și completează informațiile.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="photo-file">Imagine</Label>
              <Input
                id="photo-file"
                type="file"
                onChange={handleFileSelect}
                accept="image/jpeg,image/png,image/gif,image/webp"
              />
              {uploadPreview && (
                <div className="relative w-full h-48 rounded-lg overflow-hidden border mt-2">
                  <Image
                    src={uploadPreview}
                    alt="Preview"
                    fill
                    className="object-contain"
                  />
                  <Button
                    size="sm"
                    variant="destructive"
                    className="absolute top-2 right-2"
                    onClick={() => {
                      setUploadFile(null);
                      setUploadPreview(null);
                    }}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="photoName">Nume fotografie *</Label>
              <Input
                id="photoName"
                value={formData.photoName}
                onChange={(e) => setFormData(prev => ({ ...prev, photoName: e.target.value }))}
                placeholder="Ex: Față vehicul"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="photo-description">Descriere</Label>
              <Input
                id="photo-description"
                value={formData.description}
                onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                placeholder="Descriere opțională..."
              />
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="isPrimary"
                checked={formData.isPrimary}
                onCheckedChange={(checked) =>
                  setFormData(prev => ({ ...prev, isPrimary: checked === true }))
                }
              />
              <Label htmlFor="isPrimary" className="text-sm font-normal">
                Setează ca fotografie principală
              </Label>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsUploadOpen(false)}>
              Anulează
            </Button>
            <Button
              onClick={handleUpload}
              disabled={!uploadFile || !formData.photoName || uploadMutation.isPending}
            >
              {uploadMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              <Upload className="mr-2 h-4 w-4" />
              Încarcă
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Preview Dialog */}
      <Dialog open={!!previewPhoto} onOpenChange={() => setPreviewPhoto(null)}>
        <DialogContent className="sm:max-w-3xl">
          <DialogHeader>
            <DialogTitle>{previewPhoto?.photoName}</DialogTitle>
            {previewPhoto?.description && (
              <DialogDescription>{previewPhoto.description}</DialogDescription>
            )}
          </DialogHeader>
          <div className="relative w-full aspect-video rounded-lg overflow-hidden">
            {previewPhoto && (
              <Image
                src={documentsApi.getPhotoUrl(previewPhoto.id)}
                alt={previewPhoto.photoName}
                fill
                className="object-contain"
              />
            )}
          </div>
          {previewPhoto && (
            <div className="flex items-center justify-between text-sm text-slate-500">
              <span>
                {format(new Date(previewPhoto.createdAt), 'dd MMMM yyyy, HH:mm', { locale: ro })}
              </span>
              <span>{formatFileSize(previewPhoto.fileSize)}</span>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={!!deleteId} onOpenChange={() => setDeleteId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Șterge fotografia</AlertDialogTitle>
            <AlertDialogDescription>
              Ești sigur că vrei să ștergi această fotografie? Această acțiune nu poate fi anulată.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Anulează</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-red-600 hover:bg-red-700"
            >
              {deleteMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Șterge
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Card>
  );
}

export default PhotoManager;

// app/frontend/src/lib/components/PhotoManager.svelte
<script>
	import { onMount } from 'svelte';
	import { api } from '$lib/api';
	import Modal from './Modal.svelte';

	export let entityType;
	export let entityId;
	export let title = 'Photos';

	let photos = [];
	let loading = false;
	let showUploadModal = false;
	let showViewModal = false;
	let selectedPhoto = null;
	let uploadFile = null;
	let uploadData = {
		photoName: '',
		description: '',
		isPrimary: false
	};

	onMount(async () => {
		await loadPhotos();
	});

	async function loadPhotos() {
		loading = true;
		try {
			const response = await api.getPhotos(entityType, entityId);
			photos = response.data || [];
		} catch (error) {
			console.error('Failed to load photos:', error);
			photos = [];
		} finally {
			loading = false;
		}
	}

	function handleFileSelect(event) {
		const file = event.target.files[0];
		if (file) {
			if (!file.type.startsWith('image/')) {
				alert('Please select an image file');
				return;
			}
			uploadFile = file;
			if (!uploadData.photoName) {
				uploadData.photoName = file.name.replace(/\.[^/.]+$/, '');
			}
		}
	}

	async function handleUpload() {
		if (!uploadFile) {
			alert('Please select an image file to upload');
			return;
		}

		if (!uploadData.photoName.trim()) {
			alert('Please enter a photo name');
			return;
		}

		loading = true;
		try {
			await api.uploadPhoto(uploadFile, {
				...uploadData,
				entityType,
				entityId
			});

			showUploadModal = false;
			resetUploadForm();
			await loadPhotos();
		} catch (error) {
			console.error('Failed to upload photo:', error);
			alert('Failed to upload photo. Please try again.');
		} finally {
			loading = false;
		}
	}

	async function handleDelete(photo) {
		if (confirm(`Are you sure you want to delete "${photo.photoName}"?`)) {
			try {
				await api.deletePhoto(photo.id);
				await loadPhotos();
			} catch (error) {
				console.error('Failed to delete photo:', error);
				alert('Failed to delete photo. Please try again.');
			}
		}
	}

	function handlePhotoClick(photo) {
		selectedPhoto = photo;
		showViewModal = true;
	}

	function resetUploadForm() {
		uploadFile = null;
		uploadData = {
			photoName: '',
			description: '',
			isPrimary: false
		};

		// Reset file input
		const fileInput = document.getElementById('photo-file-input');
		if (fileInput) fileInput.value = '';
	}

	function closeUploadModal() {
		showUploadModal = false;
		resetUploadForm();
	}

	function closeViewModal() {
		showViewModal = false;
		selectedPhoto = null;
	}

	function formatDate(dateString) {
		if (!dateString) return '-';
		return new Date(dateString).toLocaleDateString();
	}

	function formatFileSize(bytes) {
		if (bytes === 0) return '0 Bytes';
		const k = 1024;
		const sizes = ['Bytes', 'KB', 'MB', 'GB'];
		const i = Math.floor(Math.log(bytes) / Math.log(k));
		return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
	}
</script>

<div class="bg-white rounded-lg shadow p-6">
	<div class="flex justify-between items-center mb-4">
		<h3 class="text-lg font-semibold text-gray-900">{title}</h3>
		<button
			on:click={() => showUploadModal = true}
			class="btn btn-primary btn-sm"
		>
			<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
			</svg>
			Upload Photo
		</button>
	</div>

	{#if loading}
		<div class="flex items-center justify-center py-8">
			<div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
		</div>
	{:else if photos.length === 0}
		<div class="text-center py-8">
			<svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/>
			</svg>
			<h3 class="mt-2 text-sm font-medium text-gray-900">No photos</h3>
			<p class="mt-1 text-sm text-gray-500">Get started by uploading a photo.</p>
		</div>
	{:else}
		<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
			{#each photos as photo}
				<div class="relative group cursor-pointer" on:click={() => handlePhotoClick(photo)}>
					<div class="aspect-square bg-gray-200 rounded-lg overflow-hidden">
						<img
							src={api.getPhotoUrl(photo.id)}
							alt={photo.photoName}
							class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-200"
							loading="lazy"
						/>
					</div>
					{#if photo.isPrimary}
						<div class="absolute top-2 left-2">
							<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-primary-100 text-primary-800">
								Primary
							</span>
						</div>
					{/if}
					<div class="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
						<button
							on:click|stopPropagation={() => handleDelete(photo)}
							class="p-1 bg-red-600 text-white rounded-full hover:bg-red-700"
							title="Delete photo"
						>
							<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
							</svg>
						</button>
					</div>
					<div class="mt-2">
						<p class="text-sm font-medium text-gray-900 truncate">{photo.photoName}</p>
						<p class="text-xs text-gray-500">{formatDate(photo.createdAt)}</p>
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

<!-- Upload Modal -->
<Modal
	open={showUploadModal}
	title="Upload Photo"
	size="md"
	on:close={closeUploadModal}
>
	<div class="space-y-4">
		<div>
			<label for="photo-file-input" class="block text-sm font-medium text-gray-700 mb-2">
				Select Image *
			</label>
			<input
				id="photo-file-input"
				type="file"
				on:change={handleFileSelect}
				class="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-medium file:bg-primary-50 file:text-primary-700 hover:file:bg-primary-100"
				accept="image/*"
				required
			/>
			{#if uploadFile}
				<div class="mt-2">
					<div class="text-sm text-gray-600">
						Selected: {uploadFile.name} ({formatFileSize(uploadFile.size)})
					</div>
					<div class="mt-2">
						<img
							src={URL.createObjectURL(uploadFile)}
							alt="Preview"
							class="h-32 w-32 object-cover rounded-lg"
						/>
					</div>
				</div>
			{/if}
		</div>

		<div>
			<label for="photo-name" class="block text-sm font-medium text-gray-700 mb-2">
				Photo Name *
			</label>
			<input
				id="photo-name"
				type="text"
				bind:value={uploadData.photoName}
				class="block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500"
				placeholder="Enter photo name"
				required
			/>
		</div>

		<div>
			<label for="photo-description" class="block text-sm font-medium text-gray-700 mb-2">
				Description
			</label>
			<textarea
				id="photo-description"
				bind:value={uploadData.description}
				rows="3"
				class="block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500"
				placeholder="Enter description (optional)"
			></textarea>
		</div>

		<div class="flex items-center">
			<input
				id="photo-primary"
				type="checkbox"
				bind:checked={uploadData.isPrimary}
				class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
			/>
			<label for="photo-primary" class="ml-2 block text-sm text-gray-900">
				Set as primary photo
			</label>
		</div>
	</div>

	<svelte:fragment slot="footer">
		<button type="button" class="btn btn-secondary" on:click={closeUploadModal}>
			Cancel
		</button>
		<button
			type="button"
			class="btn btn-primary"
			on:click={handleUpload}
			disabled={loading || !uploadFile}
		>
			{#if loading}
				<svg class="animate-spin -ml-1 mr-3 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
					<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
					<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
				</svg>
			{/if}
			Upload Photo
		</button>
	</svelte:fragment>
</Modal>

<!-- Photo View Modal -->
<Modal
	open={showViewModal}
	title={selectedPhoto?.photoName || 'Photo'}
	size="lg"
	on:close={closeViewModal}
>
	{#if selectedPhoto}
		<div class="space-y-4">
			<div class="flex justify-center">
				<img
					src={api.getPhotoUrl(selectedPhoto.id)}
					alt={selectedPhoto.photoName}
					class="max-w-full max-h-96 object-contain rounded-lg"
				/>
			</div>

			<div class="space-y-2">
				<div class="flex justify-between">
					<span class="text-sm font-medium text-gray-700">Name:</span>
					<span class="text-sm text-gray-900">{selectedPhoto.photoName}</span>
				</div>

				{#if selectedPhoto.description}
					<div class="flex justify-between">
						<span class="text-sm font-medium text-gray-700">Description:</span>
						<span class="text-sm text-gray-900">{selectedPhoto.description}</span>
					</div>
				{/if}

				<div class="flex justify-between">
					<span class="text-sm font-medium text-gray-700">Uploaded:</span>
					<span class="text-sm text-gray-900">{formatDate(selectedPhoto.createdAt)}</span>
				</div>

				<div class="flex justify-between">
					<span class="text-sm font-medium text-gray-700">File Size:</span>
					<span class="text-sm text-gray-900">{formatFileSize(selectedPhoto.fileSize)}</span>
				</div>

				{#if selectedPhoto.isPrimary}
					<div class="flex justify-between">
						<span class="text-sm font-medium text-gray-700">Status:</span>
						<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-primary-100 text-primary-800">
							Primary Photo
						</span>
					</div>
				{/if}
			</div>
		</div>
	{/if}

	<svelte:fragment slot="footer">
		<button type="button" class="btn btn-secondary" on:click={closeViewModal}>
			Close
		</button>
		{#if selectedPhoto}
			<button
				type="button"
				class="btn btn-danger"
				on:click={() => { handleDelete(selectedPhoto); closeViewModal(); }}
			>
				Delete Photo
			</button>
		{/if}
	</svelte:fragment>
</Modal>
